### ISSUE TITLE
ValueError: incorrect number of indices for array when run predict_2d.py

### ISSUE THREAD

**Issue by wenwenyu** [vuhoangminh/Brain-segmentation#2]
Hi
I'm sorry about asking this, but I have no idea to solve this problem when run predict_2d.py. the following is error message:

_Slice number:  70
Image:  IBSR_10_ana_strip.nii.gz
Traceback (most recent call last):
Number of processed patches:  2
Number of extracted patches:  2
  File "C:/Users/user/Desktop/project/code/Brain-segmentation-master/minh_2d_unet/predict_2d.py", line 254, in <module>
    predict(img_dir_name)
  File "C:/Users/user/Desktop/project/code/Brain-segmentation-master/minh_2d_unet/predict_2d.py", line 216, in predict
    if img_mask_data.item((i, j, iSlice)) == 1:
ValueError: incorrect number of indices for array_

Thinks!

**Comment by wenwenyu** [comment]
Hi, I have solved this problem. I modify predict_2d.py that change `if img_mask_data.item((i, j, iSlice)) == 1:if` to`if img_mask_data.item((i, j, iSlice, 0)) == 1:` in lines 217.
